-- Adaptation non destructive de SageSimu pour le portail client Toulemonde Production.
-- Base cible : sage_simu / schema public.
-- Ce script n'efface aucune table, aucune colonne et aucune donnee existante.

ALTER TABLE "F_COMPTET"
  ADD COLUMN IF NOT EXISTS "PORTAL_CLIENT_ID" INTEGER,
  ADD COLUMN IF NOT EXISTS "PORTAL_CLIENT_EMAIL" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "PORTAL_VAT_NUMBER" VARCHAR(80);

ALTER TABLE "F_DOCENTETE"
  ADD COLUMN IF NOT EXISTS "PORTAL_ORDER_ID" INTEGER,
  ADD COLUMN IF NOT EXISTS "PORTAL_ORDER_NUMBER" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "PORTAL_CUSTOMER_REFERENCE" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "PORTAL_STATUS" VARCHAR(60),
  ADD COLUMN IF NOT EXISTS "PORTAL_URGENT" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "PORTAL_GENERAL_COMMENT" TEXT,
  ADD COLUMN IF NOT EXISTS "PORTAL_CREATED_AT" TIMESTAMP;

ALTER TABLE "F_DOCLIGNE"
  ADD COLUMN IF NOT EXISTS "PORTAL_LINE_ID" INTEGER,
  ADD COLUMN IF NOT EXISTS "PORTAL_ORDER_ID" INTEGER,
  ADD COLUMN IF NOT EXISTS "PORTAL_LINE_NUMBER" INTEGER,
  ADD COLUMN IF NOT EXISTS "PORTAL_APPLICATION_TYPE" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "PORTAL_MATERIAL_FAMILY" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "PORTAL_MATERIAL_QUALITY" VARCHAR(160),
  ADD COLUMN IF NOT EXISTS "PORTAL_COUNT_SYSTEM" VARCHAR(40),
  ADD COLUMN IF NOT EXISTS "PORTAL_YARN_COUNT_NM" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "PORTAL_DTEX" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "PORTAL_PLY_NUMBER" VARCHAR(40),
  ADD COLUMN IF NOT EXISTS "PORTAL_TWIST_TYPE" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "PORTAL_TWIST_DIRECTION" VARCHAR(40),
  ADD COLUMN IF NOT EXISTS "PORTAL_FINISH" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "PORTAL_COLOR_MODE" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "PORTAL_COLOR_NAME" VARCHAR(160),
  ADD COLUMN IF NOT EXISTS "PORTAL_COLOR_REFERENCE" VARCHAR(160),
  ADD COLUMN IF NOT EXISTS "PORTAL_DYEING_REQUIRED" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "PORTAL_PACKAGING" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "PORTAL_QUANTITY_KG" NUMERIC(14,3),
  ADD COLUMN IF NOT EXISTS "PORTAL_TOLERANCE_PERCENT" NUMERIC(6,2),
  ADD COLUMN IF NOT EXISTS "PORTAL_PRODUCTION_COMMENT" TEXT;

ALTER TABLE "F_ARTICLE"
  ADD COLUMN IF NOT EXISTS "PORTAL_GENERIC" BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_f_comptet_portal_client_id
  ON "F_COMPTET" ("PORTAL_CLIENT_ID");

CREATE INDEX IF NOT EXISTS idx_f_docentete_portal_order_id
  ON "F_DOCENTETE" ("PORTAL_ORDER_ID");

CREATE INDEX IF NOT EXISTS idx_f_docligne_portal_order_id
  ON "F_DOCLIGNE" ("PORTAL_ORDER_ID");

CREATE INDEX IF NOT EXISTS idx_f_docligne_portal_line_id
  ON "F_DOCLIGNE" ("PORTAL_LINE_ID");

INSERT INTO "F_ARTICLE" ("AR_Ref", "AR_Design", "PORTAL_GENERIC")
SELECT 'FIL-SPECIFIQUE', 'Fil spécifique portail client', TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM "F_ARTICLE"
  WHERE "AR_Ref" = 'FIL-SPECIFIQUE'
);
