import { T } from "./theme";

export const styles = {
  profilePage: {
  display: "grid",
  gap: 22,
},

profileHeaderCard: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 24,
  background: "#fff",
  border: `1px solid ${T.border}`,
  borderRadius: 28,
  padding: "28px clamp(20px, 4vw, 34px)",
  boxShadow: T.shadowSoft,
},

profileTitle: {
  margin: "8px 0",
  fontFamily: T.fontTitle,
  fontSize: "clamp(38px, 5vw, 58px)",
  lineHeight: 1,
  fontWeight: 800,
  letterSpacing: "-0.04em",
  color: T.noir,
},

profileSubtitle: {
  margin: 0,
  maxWidth: 680,
  color: T.textSoft,
  lineHeight: 1.6,
  fontSize: 15,
},

profileIdentityCard: {
  minWidth: 270,
  display: "flex",
  alignItems: "center",
  gap: 14,
  padding: 16,
  borderRadius: 22,
  background: T.bleuPale,
  border: `1px solid ${T.bleuBorder}`,
},

profileAvatar: {
  width: 54,
  height: 54,
  borderRadius: 18,
  display: "grid",
  placeItems: "center",
  background: T.bleu,
  color: "#fff",
  fontSize: 24,
  fontWeight: 900,
  textTransform: "uppercase",
},

profileIdentityName: {
  fontWeight: 900,
  color: T.noir,
},

profileIdentityMeta: {
  marginTop: 4,
  color: T.textSoft,
  fontSize: 13,
},

profileSection: {
  background: "#fff",
  border: `1px solid ${T.border}`,
  borderRadius: 28,
  padding: 0,
  overflow: "hidden",
  boxShadow: T.shadowSoft,
},

profileSectionHeader: {
  padding: "22px 26px",
  borderBottom: `1px solid ${T.border}`,
  background: "linear-gradient(180deg, #ffffff 0%, #fafafa 100%)",
},

profileSectionTitle: {
  margin: 0,
  fontSize: 22,
  fontWeight: 800,
  color: T.noir,
},

profileSectionText: {
  margin: "6px 0 0",
  color: T.textSoft,
  fontSize: 13,
  lineHeight: 1.5,
},

profileFormGrid: {
  display: "grid",
  gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  gap: 18,
  padding: 26,
},

profileField: {
  display: "grid",
  gap: 8,
},

profileFieldFull: {
  gridColumn: "1 / -1",
},

profileLabel: {
  fontSize: 11,
  fontWeight: 900,
  color: "rgba(17,24,39,0.56)",
  textTransform: "uppercase",
  letterSpacing: "0.10em",
},

profileInput: {
  width: "100%",
  boxSizing: "border-box",
  height: 52,
  padding: "0 16px",
  borderRadius: 16,
  border: "1px solid rgba(17,24,39,0.11)",
  background: "#f9fafb",
  color: T.noir,
  fontSize: 15,
  outline: "none",
  transition: "all 0.2s ease",
},

profileActions: {
  display: "flex",
  justifyContent: "flex-end",
},
  shell: { minHeight: "100vh", background: T.ecru, color: T.noir, fontFamily: T.fontBody },
  appTopBar: { height: 72, background: "#050505", color: "#fff", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 clamp(14px, 3vw, 32px)", position: "sticky", top: 0, zIndex: 140, boxSizing: "border-box", borderBottom: `1px solid rgba(255,255,255,0.10)` },
  topBarLeft: { display: "flex", alignItems: "center", gap: 16, minWidth: 0 },
  panelButton: { width: 46, height: 46, borderRadius: 12, border: "1px solid rgba(255,255,255,0.20)", background: "rgba(255,255,255,0.06)", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all 0.2s ease" },
  headerLogo: { height: 36, width: "auto", objectFit: "contain", display: "block", transition: "transform 0.25s ease-in-out", transformOrigin: "center" },
  headerLogoClosed: { transform: "rotate(0deg)" },
  headerLogoOpen: { transform: "rotate(90deg) translateX(-4px)" },
  menuButton: { width: 48, height: 48, borderRadius: "50%", border: "1px solid rgba(255,255,255,0.22)", background: "rgba(255,255,255,0.06)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 5, cursor: "pointer", padding: 0, justifySelf: "end" },
  menuLine: { width: 19, height: 2, background: "#fff", borderRadius: 999, transition: "all 0.22s ease" },
  menuLineTopOpen: { transform: "translateY(7px) rotate(45deg)" },
  menuLineMiddleOpen: { opacity: 0 },
  menuLineBottomOpen: { transform: "translateY(-7px) rotate(-45deg)" },
  brandLockup: { display: "flex", alignItems: "center", gap: 14, minWidth: 0 },
  brandRule: { width: 112, height: 1, background: "rgba(255,255,255,0.42)" },
  brandText: { letterSpacing: "0.22em", fontWeight: 800, fontSize: "clamp(12px, 2vw, 15px)", whiteSpace: "nowrap", textTransform: "uppercase" },
  headerActions: { display: "flex", alignItems: "center", gap: 10 },
  headerActionButton: { border: "1px solid rgba(255,255,255,0.20)", background: "transparent", color: "#fff", borderRadius: 999, padding: "9px 14px", cursor: "pointer", fontSize: 11, letterSpacing: "0.12em", textTransform: "uppercase", fontWeight: 800 },
  menuOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.28)", border: 0, zIndex: 110, cursor: "default" },
  menuDrawer: { position: "fixed", top: 72, left: 0, bottom: 0, background: "#fff", borderRight: `1px solid ${T.border}`, boxShadow: T.shadowSoft, padding: 14, display: "flex", flexDirection: "column", gap: 18, transition: "width 0.25s ease, transform 0.25s ease, opacity 0.25s ease", zIndex: 130, boxSizing: "border-box", overflowY: "auto", overflowX: "hidden" },
  menuDrawerVisible: { transform: "translateX(0)", opacity: 1, pointerEvents: "auto" },
  menuDrawerHidden: { transform: "translateX(-100%)", opacity: 0, pointerEvents: "none" },
  menuDrawerExpanded: { width: 288 },
  menuDrawerCollapsed: { width: 76 },
  menuDrawerMobile: { width: "min(320px, 86vw)", boxShadow: "0 28px 70px rgba(0,0,0,0.28)" },
  menuLogoPanel: { background: "#fff", border: `1px solid ${T.border}`, borderRadius: 12, padding: 12, display: "grid", gap: 10, justifyItems: "center" },
  menuLogo: { width: 42, height: "auto", objectFit: "contain" },
  menuSubtitle: { color: T.textSoft, fontSize: 12, lineHeight: 1.5 },
  menuSectionLabel: { margin: "10px 4px 0", color: T.textSoft, fontSize: 10, letterSpacing: "0.22em", textTransform: "uppercase" },
  nav: { display: "grid", gap: 8 },
  navItem: { minHeight: 46, padding: "0 13px", borderRadius: 12, textDecoration: "none", border: `1px solid ${T.border}`, fontSize: 12, fontWeight: 800, letterSpacing: "0.03em", textTransform: "uppercase", transition: "all 0.18s ease", display: "flex", alignItems: "center", gap: 11, whiteSpace: "nowrap" },
  navItemCollapsed: { width: 46, padding: 0, justifyContent: "center" },
  logoutButton: { minHeight: 46, border: `1px solid ${T.borderMid}`, background: "transparent", borderRadius: 12, padding: "0 13px", cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em", color: T.noir, display: "flex", alignItems: "center", gap: 11, marginTop: "auto", whiteSpace: "nowrap" },
  logoutButtonCollapsed: { width: 46, padding: 0, justifyContent: "center" },
  brand: { color: T.bleu, letterSpacing: "0.28em", fontWeight: 800, fontSize: 13 },
  ghostButton: { border: `1px solid ${T.border}`, background: "transparent", borderRadius: 6, padding: "12px 14px", cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em" },
  main: { padding: "28px clamp(18px, 3vw, 34px) 46px", minWidth: 0, boxSizing: "border-box", transition: "margin-left 0.25s ease", maxWidth: 1510 },
  topbar: { display: "flex", justifyContent: "space-between", gap: 18, alignItems: "center", marginBottom: 24, flexWrap: "wrap" },
  overline: { fontSize: 11, letterSpacing: "0.24em", textTransform: "uppercase", color: T.textSoft },
  pageHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 18, marginBottom: 4, flexWrap: "wrap" },
  pageHeaderText: { minWidth: 0 },
  pageHeaderKicker: { margin: 0, fontFamily: T.fontTitle, fontSize: 11, fontWeight: 800, letterSpacing: "0.18em", textTransform: "uppercase", color: T.textSoft },
  pageHeaderKickerClient: { color: T.bleu },
  pageHeaderKickerAdmin: { color: T.textSoft },
  pageHeaderTitle: { margin: "8px 0 0", fontFamily: T.fontTitle, color: T.noir, fontSize: "clamp(32px, 4vw, 48px)", lineHeight: 1.02, fontWeight: 800, letterSpacing: "-0.04em" },
  pageHeaderSubtitle: { margin: "10px 0 0", maxWidth: 760, fontFamily: T.fontBody, fontSize: 15, lineHeight: 1.6, fontWeight: 400, color: T.textSoft },
  pageHeaderActions: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 10, flexWrap: "wrap" },
  pageTitle: { margin: "6px 0 0", fontFamily: T.fontTitle, color: T.noir, fontSize: "clamp(32px, 4vw, 48px)", lineHeight: 1.02, fontWeight: 800, letterSpacing: "-0.04em" },
  loginPage: { minHeight: "100vh", background: T.ecru, display: "grid", placeItems: "center", fontFamily: T.fontBody, padding: 20, boxSizing: "border-box" },
  loginCard: { width: "min(430px, 100%)", background: T.blanc, border: `1px solid ${T.border}`, borderRadius: 8, padding: 28, display: "grid", gap: 14, boxShadow: "0 24px 60px rgba(0,0,0,0.08)" },
  loginTitle: { fontFamily: T.fontTitle, fontSize: 38, margin: "8px 0 0", color: T.bleu, fontWeight: 800, lineHeight: 1, letterSpacing: "-0.04em" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  pageStack: { display: "grid", gap: 20 },
  heroPanel: { minHeight: 430, position: "relative", overflow: "hidden", borderRadius: T.cardRadius, padding: "42px clamp(22px, 5vw, 58px)", display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 18, boxShadow: T.shadowSoft, flexWrap: "wrap", background: "#050505" },
  heroImage: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", filter: "grayscale(1)", transform: "scale(1.02)" },
  heroOverlay: { position: "absolute", inset: 0, background: "linear-gradient(90deg, rgba(0,0,0,0.72), rgba(0,0,0,0.34) 55%, rgba(0,0,0,0.15))" },
  heroContent: { position: "relative", zIndex: 1, maxWidth: 760 },
  overlineLight: { fontSize: 11, letterSpacing: "0.24em", textTransform: "uppercase", color: "rgba(255,255,255,0.70)" },
  heroTitle: { fontFamily: T.fontTitle, color: "#fff", fontSize: "clamp(42px, 7vw, 76px)", lineHeight: 0.95, margin: "12px 0", fontWeight: 800, letterSpacing: "-0.04em", maxWidth: 820 },
  heroText: { color: "rgba(255,255,255,0.78)", margin: 0, lineHeight: 1.55, maxWidth: 620, fontSize: 17 },
  dashboardGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1.45fr) minmax(280px, 0.75fr)", gap: 20, alignItems: "start" },
  dashboardGridMobile: { gridTemplateColumns: "1fr" },
  quickActions: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12 },
  quickButton: { border: `1px solid ${T.border}`, background: "#fff", color: T.noir, borderRadius: 12, padding: "15px 16px", cursor: "pointer", fontWeight: 800, textAlign: "left", textTransform: "uppercase", letterSpacing: "0.06em", boxShadow: "0 10px 24px rgba(0,0,0,0.035)" },
  card: { background: T.blanc, border: `1px solid ${T.border}`, borderRadius: T.cardRadius, padding: 18 },
  cardWide: { background: T.blanc, border: `1px solid ${T.border}`, borderRadius: T.cardRadius, padding: "22px clamp(16px, 3vw, 28px)", display: "grid", gap: 16, boxShadow: T.shadowSoft },
  cardTitle: { fontFamily: T.fontTitle, fontSize: 20, margin: 0, color: T.noir, fontWeight: 800, letterSpacing: "-0.02em" },
  metricTitle: { fontSize: 11, color: T.textSoft, textTransform: "uppercase", letterSpacing: "0.18em" },
  metricValue: { fontFamily: T.fontTitle, fontSize: 34, marginTop: 8, fontWeight: 800, letterSpacing: "-0.03em" },
  wizardShell: { background: T.blanc, border: `1px solid ${T.border}`, borderRadius: T.cardRadius, padding: "22px clamp(16px, 3vw, 28px)", display: "grid", gap: 18, boxShadow: T.shadowSoft, overflow: "hidden" },
  wizardHeader: { display: "grid", gridTemplateColumns: "minmax(0,1fr) 220px", gap: 18, alignItems: "center" },
  wizardHeaderMobile: { gridTemplateColumns: "1fr" },
  wizardImage: { width: "100%", height: 130, objectFit: "cover", filter: "grayscale(1)", borderRadius: 14 },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 12 },
  field: { display: "grid", gap: 6, textAlign: "left" },
  label: { fontSize: 11, letterSpacing: "0.14em", textTransform: "uppercase", color: T.textSoft },
  inlineError: { color: T.danger, fontSize: 12 },
  input: { border: `1px solid ${T.border}`, background: "#fff", borderRadius: 10, padding: "12px 12px", font: "inherit", width: "100%", minWidth: 0 },
  textarea: { border: `1px solid ${T.border}`, background: "#fff", borderRadius: 10, padding: "12px 12px", minHeight: 96, font: "inherit", width: "100%" },
  checkLine: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, marginTop: 22 },
  primaryButton: { border: "none", background: T.bleu, color: "#fff", borderRadius: 6, padding: "12px 16px", cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em" },
  formActions: { display: "flex", justifyContent: "space-between", gap: 12, marginTop: 4 },
  stepper: { display: "flex", gap: 8, flexWrap: "wrap" },
  stepPill: { border: `1px solid ${T.border}`, background: "#fff", color: T.noir, borderRadius: 12, padding: "10px 12px", cursor: "pointer", fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em", display: "inline-flex", alignItems: "center", gap: 8 },
  stepPillActive: { background: T.bleu, color: "#fff", borderColor: T.bleu },
  stepNumber: { fontSize: 10, opacity: 0.72 },
  fileName: { color: T.textSoft, fontSize: 12 },
  uploadPanel: { minHeight: 230, background: T.ecru, border: `1px solid ${T.border}`, borderRadius: 14, padding: 22, display: "grid", gap: 18, alignContent: "center" },
  uploadTitle: { fontFamily: T.fontTitle, fontSize: 20, lineHeight: 1.15, margin: 0, fontWeight: 800, letterSpacing: "-0.02em" },
  profileHero: { minHeight: 310, position: "relative", overflow: "hidden", borderRadius: T.cardRadius, padding: "38px clamp(22px, 5vw, 58px)", display: "flex", alignItems: "flex-end", boxShadow: T.shadowSoft, background: "#050505" },
  profileHeroImage: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", filter: "grayscale(1)" },
  summaryGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12 },
  summaryItem: { background: T.ecru, border: `1px solid ${T.border}`, borderRadius: 8, padding: 12 },
  muted: { color: T.textSoft, lineHeight: 1.5 },
  helpText: { fontSize: 12, color: T.textSoft, lineHeight: 1.4 },
  error: { background: "rgba(159,29,29,0.08)", color: T.danger, border: "1px solid rgba(159,29,29,0.22)", borderRadius: 6, padding: 10 },
  success: { background: "rgba(35,107,56,0.08)", color: T.green, border: "1px solid rgba(35,107,56,0.22)", borderRadius: 6, padding: 10 },
  table: { display: "grid", border: `1px solid ${T.border}`, borderRadius: 8, overflow: "auto", background: "#fff" },
  tableHead: { padding: 12, background: T.ecru, fontSize: 11, textTransform: "uppercase", letterSpacing: "0.12em", color: T.textSoft },
  cell: { padding: 12, borderTop: `1px solid ${T.border}`, fontSize: 13 },
  badge: { display: "inline-flex", padding: "5px 8px", background: T.bleuPale, color: T.bleu, border: `1px solid ${T.bleuBorder}`, borderRadius: 6, fontSize: 11, textTransform: "uppercase", fontWeight: 800 },
  emptyState: { padding: 18, background: T.ecru, borderRadius: 8, color: T.textSoft },
  linkButton: { border: "none", background: "transparent", color: T.bleu, cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em", padding: 0, fontSize: 12, textAlign: "left" },
  adminShell: { minHeight: "100vh", display: "grid", gridTemplateColumns: "290px minmax(0, 1fr)", background: T.ecru, color: T.noir, fontFamily: T.fontBody },
  adminSidebar: { position: "sticky", top: 0, height: "100vh", background: "#050505", color: "#fff", padding: 18, display: "flex", flexDirection: "column", justifyContent: "space-between", gap: 20, boxSizing: "border-box" },
  adminBrand: { display: "flex", alignItems: "center", gap: 14, padding: "10px 8px 24px", borderBottom: "1px solid rgba(255,255,255,0.12)" },
  adminLogo: { height: 34, objectFit: "contain" },
  adminBrandTitle: { fontSize: 13, fontWeight: 900, letterSpacing: "0.14em", textTransform: "uppercase" },
  adminBrandSub: { fontSize: 12, color: "rgba(255,255,255,0.62)", marginTop: 4 },
  adminNav: { display: "grid", gap: 8, marginTop: 18 },
  adminNavItem: { minHeight: 44, padding: "0 12px", borderRadius: 12, color: "rgba(255,255,255,0.76)", textDecoration: "none", display: "flex", alignItems: "center", gap: 10, fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em", border: "1px solid transparent" },
  adminNavItemActive: { color: "#fff", background: "rgba(0,0,254,0.42)", borderColor: "rgba(255,255,255,0.16)" },
  adminLogoutButton: { minHeight: 44, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(255,255,255,0.06)", color: "#fff", borderRadius: 12, padding: "0 12px", display: "flex", alignItems: "center", gap: 10, cursor: "pointer", fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em" },
  adminMain: { padding: "28px clamp(18px, 3vw, 38px) 48px", minWidth: 0 },
  adminPageHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 18, marginBottom: 4, flexWrap: "wrap" },
};
