import { T } from "./theme";

export const styles = {
  profilePage: {
  display: "grid",
  gap: 22,
},

profileHeaderCard: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 24,
  background: "#fff",
  border: `1px solid ${T.border}`,
  borderRadius: 28,
  padding: "28px clamp(20px, 4vw, 34px)",
  boxShadow: T.shadowSoft,
},

profileTitle: {
  margin: "8px 0",
  fontFamily: T.fontTitle,
  fontSize: "clamp(38px, 5vw, 58px)",
  lineHeight: 1,
  fontWeight: 800,
  letterSpacing: "-0.04em",
  color: T.noir,
},

profileSubtitle: {
  margin: 0,
  maxWidth: 680,
  color: T.textSoft,
  lineHeight: 1.6,
  fontSize: 15,
},

profileIdentityCard: {
  minWidth: 270,
  display: "flex",
  alignItems: "center",
  gap: 14,
  padding: 16,
  borderRadius: 22,
  background: T.bleuPale,
  border: `1px solid ${T.bleuBorder}`,
},

profileAvatar: {
  width: 54,
  height: 54,
  borderRadius: 18,
  display: "grid",
  placeItems: "center",
  background: T.bleu,
  color: "#fff",
  fontSize: 24,
  fontWeight: 900,
  textTransform: "uppercase",
},

profileIdentityName: {
  fontWeight: 900,
  color: T.noir,
},

profileIdentityMeta: {
  marginTop: 4,
  color: T.textSoft,
  fontSize: 13,
},

profileSection: {
  background: "#fff",
  border: `1px solid ${T.border}`,
  borderRadius: 28,
  padding: 0,
  overflow: "hidden",
  boxShadow: T.shadowSoft,
},

profileSectionHeader: {
  padding: "22px 26px",
  borderBottom: `1px solid ${T.border}`,
  background: "linear-gradient(180deg, #ffffff 0%, #fafafa 100%)",
},

profileSectionTitle: {
  margin: 0,
  fontSize: 22,
  fontWeight: 800,
  color: T.noir,
},

profileSectionText: {
  margin: "6px 0 0",
  color: T.textSoft,
  fontSize: 13,
  lineHeight: 1.5,
},

profileFormGrid: {
  display: "grid",
  gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  gap: 18,
  padding: 26,
},

profileField: {
  display: "grid",
  gap: 8,
},

profileFieldFull: {
  gridColumn: "1 / -1",
},

profileLabel: {
  fontSize: 11,
  fontWeight: 900,
  color: "rgba(17,24,39,0.56)",
  textTransform: "uppercase",
  letterSpacing: "0.10em",
},

profileInput: {
  width: "100%",
  boxSizing: "border-box",
  height: 52,
  padding: "0 16px",
  borderRadius: 16,
  border: "1px solid rgba(17,24,39,0.11)",
  background: "#f9fafb",
  color: T.noir,
  fontSize: 15,
  outline: "none",
  transition: "all 0.2s ease",
},

profileActions: {
  display: "flex",
  justifyContent: "flex-end",
},
  shell: { minHeight: "100vh", background: T.ecru, color: T.noir, fontFamily: T.fontBody },
appTopBar: {
  height: 72,
  background: T.deepBlack,
  color: "#fff",
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  padding: "0 clamp(14px, 3vw, 32px)",
  position: "sticky",
  top: 0,
  zIndex: 1000,
  boxSizing: "border-box",
  borderBottom: `1px solid rgba(255,255,255,0.10)`,
},  topBarLeft: { display: "flex", alignItems: "center", gap: 16, minWidth: 0 },
  panelButton: { width: 46, height: 46, borderRadius: 12, border: "1px solid rgba(255,255,255,0.20)", background: "rgba(255,255,255,0.06)", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all 0.2s ease" },
  headerLogo: { height: 36, width: "auto", objectFit: "contain", display: "block", transition: "transform 0.25s ease-in-out", transformOrigin: "center" },
  headerLogoClosed: { transform: "rotate(0deg)" },
  headerLogoOpen: { transform: "rotate(90deg) translateX(-4px)" },
  menuButton: { width: 48, height: 48, borderRadius: "50%", border: "1px solid rgba(255,255,255,0.22)", background: "rgba(255,255,255,0.06)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 5, cursor: "pointer", padding: 0, justifySelf: "end" },
  menuLine: { width: 19, height: 2, background: "#fff", borderRadius: 999, transition: "all 0.22s ease" },
  menuLineTopOpen: { transform: "translateY(7px) rotate(45deg)" },
  menuLineMiddleOpen: { opacity: 0 },
  menuLineBottomOpen: { transform: "translateY(-7px) rotate(-45deg)" },
  brandLockup: { display: "flex", alignItems: "center", gap: 14, minWidth: 0 },
  brandRule: { width: 112, height: 1, background: "rgba(255,255,255,0.42)" },
  brandText: { letterSpacing: "0.22em", fontWeight: 800, fontSize: "clamp(12px, 2vw, 15px)", whiteSpace: "nowrap", textTransform: "uppercase" },
  headerActions: { display: "flex", alignItems: "center", gap: 10 },
  headerActionButton: { border: "1px solid rgba(255,255,255,0.20)", background: "transparent", color: "#fff", borderRadius: 999, padding: "9px 14px", cursor: "pointer", fontSize: 11, letterSpacing: "0.12em", textTransform: "uppercase", fontWeight: 800 },
  menuOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.28)", border: 0, zIndex: 110, cursor: "default" },
  menuDrawer: { position: "fixed", top: 72, left: 0, bottom: 0, background: "#fff", borderRight: `1px solid ${T.border}`, boxShadow: T.shadowSoft, padding: 14, display: "flex", flexDirection: "column", gap: 18, transition: "width 0.25s ease, transform 0.25s ease, opacity 0.25s ease", zIndex: 130, boxSizing: "border-box", overflowY: "auto", overflowX: "hidden" },
  menuDrawerVisible: { transform: "translateX(0)", opacity: 1, pointerEvents: "auto" },
  menuDrawerHidden: { transform: "translateX(-100%)", opacity: 0, pointerEvents: "none" },
  menuDrawerExpanded: { width: 288 },
  menuDrawerCollapsed: { width: 76 },
  menuDrawerMobile: { width: "min(320px, 86vw)", boxShadow: "0 28px 70px rgba(0,0,0,0.28)" },
  menuLogoPanel: { background: "#fff", border: `1px solid ${T.border}`, borderRadius: 12, padding: 12, display: "grid", gap: 10, justifyItems: "center" },
  menuLogo: { width: 42, height: "auto", objectFit: "contain" },
  menuSubtitle: { color: T.textSoft, fontSize: 12, lineHeight: 1.5 },
  menuSectionLabel: { margin: "10px 4px 0", color: T.textSoft, fontSize: 10, letterSpacing: "0.22em", textTransform: "uppercase" },
  nav: { display: "grid", gap: 8 },
  navItem: { minHeight: 48, padding: "0 13px", borderRadius: 14, textDecoration: "none", border: `1px solid ${T.border}`, fontSize: 12, fontWeight: 800, letterSpacing: "0.03em", textTransform: "uppercase", transition: "all 0.18s ease", display: "flex", alignItems: "center", gap: 11, whiteSpace: "nowrap" },
  navItemCollapsed: { width: 46, padding: 0, justifyContent: "center" },
  logoutButton: { minHeight: 48, border: `1px solid ${T.borderMid}`, background: "transparent", borderRadius: 14, padding: "0 13px", cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em", color: T.noir, display: "flex", alignItems: "center", gap: 11, marginTop: "auto", whiteSpace: "nowrap" },
  logoutButtonCollapsed: { width: 46, padding: 0, justifyContent: "center" },
  brand: { color: T.bleu, letterSpacing: "0.28em", fontWeight: 800, fontSize: 13 },
  ghostButton: { minHeight: 44, border: `1px solid ${T.border}`, background: "#fff", color: T.noir, borderRadius: 12, padding: "0 16px", cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em", display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, boxShadow: "0 8px 18px rgba(0,0,0,0.035)" },
  main: { width: "auto", maxWidth: "100%", minHeight: "calc(100vh - 72px)", overflowX: "hidden", padding: "32px 32px 48px", minWidth: 0, boxSizing: "border-box", transition: "margin-left 0.25s ease" },
  mainInner: { width: "100%", maxWidth: 1480, margin: "0 auto", boxSizing: "border-box", minWidth: 0 },
  topbar: { display: "flex", justifyContent: "space-between", gap: 18, alignItems: "center", marginBottom: 24, flexWrap: "wrap" },
  overline: { fontSize: 11, letterSpacing: "0.24em", textTransform: "uppercase", color: T.textSoft },
  pageContainer: { width: "100%", maxWidth: 1440, margin: "0 auto", display: "grid", gap: 24, boxSizing: "border-box", minWidth: 0 },
  pageHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 18, marginBottom: 0, padding: 0, flexWrap: "wrap" },
  pageHeaderText: { minWidth: 0 },
  pageHeaderKicker: { margin: 0, fontFamily: T.fontTitle, fontSize: 11, fontWeight: 800, letterSpacing: "0.18em", textTransform: "uppercase", color: T.textSoft },
  pageHeaderKickerClient: { color: T.bleu },
  pageHeaderKickerAdmin: { color: T.textSoft },
  pageHeaderTitle: { margin: "8px 0 0", fontFamily: T.fontTitle, color: T.noir, fontSize: "clamp(32px, 4vw, 48px)", lineHeight: 1.02, fontWeight: 800, letterSpacing: "-0.04em" },
  pageHeaderSubtitle: { margin: "10px 0 0", maxWidth: 760, fontFamily: T.fontBody, fontSize: 15, lineHeight: 1.6, fontWeight: 400, color: T.textSoft },
  pageHeaderActions: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 10, flexWrap: "wrap" },
  pageTitle: { margin: "6px 0 0", fontFamily: T.fontTitle, color: T.noir, fontSize: "clamp(32px, 4vw, 48px)", lineHeight: 1.02, fontWeight: 800, letterSpacing: "-0.04em" },
  loginPage: { minHeight: "100vh", background: T.ecru, display: "grid", placeItems: "center", fontFamily: T.fontBody, padding: 20, boxSizing: "border-box" },
  loginCard: { width: "min(430px, 100%)", background: T.blanc, border: `1px solid ${T.border}`, borderRadius: 8, padding: 28, display: "grid", gap: 14, boxShadow: "0 24px 60px rgba(0,0,0,0.08)" },
  loginTitle: { fontFamily: T.fontTitle, fontSize: 38, margin: "8px 0 0", color: T.bleu, fontWeight: 800, lineHeight: 1, letterSpacing: "-0.04em" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  pageStack: { width: "100%", maxWidth: 1440, margin: "0 auto", display: "grid", gap: 24, boxSizing: "border-box", minWidth: 0 },
  heroPanel: { minHeight: 260, position: "relative", overflow: "hidden", borderRadius: 24, padding: "32px 38px", display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 18, boxShadow: T.shadowSoft, flexWrap: "wrap", background: T.deepBlack },
  heroImage: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", filter: "grayscale(1)", transform: "scale(1.02)" },
  heroOverlay: { position: "absolute", inset: 0, background: "linear-gradient(90deg, rgba(0,0,0,0.72), rgba(0,0,0,0.34) 55%, rgba(0,0,0,0.15))" },
  heroContent: { position: "relative", zIndex: 1, maxWidth: 760 },
  overlineLight: { fontSize: 11, letterSpacing: "0.24em", textTransform: "uppercase", color: "rgba(255,255,255,0.70)" },
  heroTitle: { fontFamily: T.fontTitle, color: "#fff", fontSize: "clamp(34px, 4vw, 52px)", lineHeight: 1, margin: "10px 0", fontWeight: 800, letterSpacing: "-0.04em", maxWidth: 760 },
  heroText: { color: "rgba(255,255,255,0.78)", margin: 0, lineHeight: 1.55, maxWidth: 560, fontSize: 15 },
  dashboardGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1.2fr) minmax(280px, 0.8fr)", gap: 20, alignItems: "start" },
  dashboardGridMobile: { gridTemplateColumns: "1fr" },
  quickActions: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12 },
  quickButton: { display: "flex", alignItems: "center", gap: 10, minHeight: 54, padding: "0 18px", borderRadius: 16, border: `1px solid ${T.border}`, background: "#fff", boxShadow: "0 12px 28px rgba(0,0,0,0.05)", cursor: "pointer", fontWeight: 800, transition: "transform 0.18s ease, box-shadow 0.18s ease, border-color 0.18s ease", textAlign: "left", color: T.noir },
  card: { background: T.blanc, border: `1px solid ${T.border}`, borderRadius: 18, padding: 18, boxShadow: T.shadowSoft },
  cardWide: { background: T.blanc, border: `1px solid ${T.border}`, borderRadius: 18, padding: "22px clamp(16px, 3vw, 28px)", display: "grid", gap: 18, boxShadow: T.shadowSoft, minWidth: 0, boxSizing: "border-box" },
  cardTitle: { fontFamily: T.fontTitle, fontSize: 20, lineHeight: 1.15, margin: 0, color: T.noir, fontWeight: 800, letterSpacing: "-0.02em" },
  metricTitle: { fontSize: 11, color: T.textSoft, textTransform: "uppercase", letterSpacing: "0.18em" },
  metricValue: { fontFamily: T.fontTitle, fontSize: 34, marginTop: 8, fontWeight: 800, letterSpacing: "-0.03em" },
  wizardShell: { background: T.blanc, border: `1px solid ${T.border}`, borderRadius: 18, padding: "22px clamp(16px, 3vw, 28px)", display: "grid", gap: 18, boxShadow: T.shadowSoft, overflow: "hidden" },
  wizardHeader: { display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(160px, 220px)", gap: 18, alignItems: "center", minWidth: 0 },
  wizardHeaderMobile: { gridTemplateColumns: "1fr" },
  wizardImage: { width: "100%", maxWidth: 220, height: 120, objectFit: "cover", filter: "grayscale(1)", borderRadius: 14, justifySelf: "end" },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))", gap: 16 },
  field: { display: "grid", gap: 8, textAlign: "left", minWidth: 0 },
  label: { fontSize: 11, letterSpacing: "0.14em", textTransform: "uppercase", color: T.textSoft, fontWeight: 800 },
  inlineError: { color: T.danger, fontSize: 12 },
  input: { minHeight: 46, border: `1px solid ${T.border}`, background: "#fff", borderRadius: 12, padding: "0 14px", font: "inherit", width: "100%", minWidth: 0, boxSizing: "border-box", outline: "none" },
  textarea: { border: `1px solid ${T.border}`, background: "#fff", borderRadius: 12, padding: "12px 14px", minHeight: 108, font: "inherit", width: "100%", minWidth: 0, boxSizing: "border-box", outline: "none", resize: "vertical" },
  checkLine: { minHeight: 46, display: "flex", alignItems: "center", gap: 9, fontSize: 13, marginTop: 0 },
  primaryButton: { minHeight: 44, border: "none", background: T.bleu, color: "#fff", borderRadius: 12, padding: "0 16px", cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em", display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, boxShadow: "0 12px 24px rgba(0,0,254,0.16)" },
  formActions: { display: "flex", justifyContent: "flex-start", alignItems: "center", gap: 12, marginTop: 4, flexWrap: "wrap" },
  stepper: { display: "flex", gap: 8, flexWrap: "wrap" },
  stepPill: { border: `1px solid ${T.border}`, background: "#fff", color: T.noir, borderRadius: 12, padding: "10px 12px", cursor: "pointer", fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em", display: "inline-flex", alignItems: "center", gap: 8 },
  stepPillActive: { background: T.bleu, color: "#fff", borderColor: T.bleu },
  stepNumber: { fontSize: 10, opacity: 0.72 },
  fileName: { color: T.textSoft, fontSize: 12 },
  uploadPanel: { minHeight: 230, background: T.ecru, border: `1px solid ${T.border}`, borderRadius: 14, padding: 22, display: "grid", gap: 18, alignContent: "center" },
  uploadTitle: { fontFamily: T.fontTitle, fontSize: 20, lineHeight: 1.15, margin: 0, fontWeight: 800, letterSpacing: "-0.02em" },
  profileHero: { minHeight: 310, position: "relative", overflow: "hidden", borderRadius: T.cardRadius, padding: "38px clamp(22px, 5vw, 58px)", display: "flex", alignItems: "flex-end", boxShadow: T.shadowSoft, background: T.deepBlack },
  profileHeroImage: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", filter: "grayscale(1)" },
  summaryGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12 },
  summaryItem: { background: T.ecru, border: `1px solid ${T.border}`, borderRadius: 14, padding: 14 },
  muted: { color: T.textSoft, lineHeight: 1.5 },
  helpText: { fontSize: 12, color: T.textSoft, lineHeight: 1.4 },
  error: { background: "rgba(159,29,29,0.08)", color: T.danger, border: "1px solid rgba(159,29,29,0.22)", borderRadius: 12, padding: "12px 14px", fontWeight: 700 },
  success: { background: "rgba(35,107,56,0.08)", color: T.green, border: "1px solid rgba(35,107,56,0.22)", borderRadius: 12, padding: "12px 14px", fontWeight: 700 },
  table: { display: "grid", border: `1px solid ${T.border}`, borderRadius: 14, overflow: "auto", background: "#fff", minWidth: 0 },
  tableHead: { padding: "13px 14px", background: T.ecru, fontSize: 11, textTransform: "uppercase", letterSpacing: "0.12em", color: T.textSoft, fontWeight: 900 },
  cell: { padding: "13px 14px", borderTop: `1px solid ${T.border}`, fontSize: 13, display: "flex", alignItems: "center", minWidth: 0, overflow: "hidden", lineHeight: 1.35 },
  badge: { display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "5px 9px", background: T.bleuPale, color: T.bleu, border: `1px solid ${T.bleuBorder}`, borderRadius: 999, fontSize: 11, textTransform: "uppercase", fontWeight: 800, whiteSpace: "normal", textAlign: "center", lineHeight: 1.2, maxWidth: "100%", overflowWrap: "anywhere" },
  emptyState: { padding: 18, background: T.ecru, border: `1px solid ${T.border}`, borderRadius: 14, color: T.textSoft },
  linkButton: { minHeight: 28, border: "none", background: "transparent", color: T.bleu, cursor: "pointer", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em", padding: 0, fontSize: 12, textAlign: "left", display: "inline-flex", alignItems: "center", gap: 6 },
  modalOverlay: { position: "fixed", inset: 0, zIndex: 500, background: "rgba(0,0,0,0.32)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  modal: { width: "min(560px, 100%)", background: "#fff", borderRadius: 18, padding: 22, display: "grid", gap: 16, boxShadow: T.shadowModal },
  fieldErrorRing: { borderRadius: 12, boxShadow: `0 0 0 1px ${T.danger}` },
  adminShell: { minHeight: "100vh", display: "grid", gridTemplateColumns: "290px minmax(0, 1fr)", background: T.ecru, color: T.noir, fontFamily: T.fontBody },
  adminSidebar: { position: "sticky", top: 0, height: "100vh", background: T.deepBlack, color: "#fff", padding: 18, display: "flex", flexDirection: "column", justifyContent: "space-between", gap: 20, boxSizing: "border-box" },
  adminBrand: { display: "flex", alignItems: "center", gap: 14, padding: "10px 8px 24px", borderBottom: "1px solid rgba(255,255,255,0.12)" },
  adminLogo: { height: 34, objectFit: "contain" },
  adminBrandTitle: { fontSize: 13, fontWeight: 900, letterSpacing: "0.14em", textTransform: "uppercase" },
  adminBrandSub: { fontSize: 12, color: "rgba(255,255,255,0.62)", marginTop: 4 },
  adminNav: { display: "grid", gap: 8, marginTop: 18 },
  adminNavItem: { minHeight: 46, padding: "0 12px", borderRadius: 14, color: "rgba(255,255,255,0.76)", textDecoration: "none", display: "flex", alignItems: "center", gap: 10, fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em", border: "1px solid transparent" },
  adminNavItemActive: { color: "#fff", background: "rgba(0,0,254,0.42)", borderColor: "rgba(255,255,255,0.16)" },
  adminNavBadge: { marginLeft: "auto", minWidth: 22, height: 22, padding: "0 7px", borderRadius: 999, background: T.bleu, color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 900, letterSpacing: 0 },
  adminSidebarFooter: { display: "grid", gap: 12 },
  adminLogoutButton: { minHeight: 46, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(255,255,255,0.06)", color: "#fff", borderRadius: 14, padding: "0 12px", display: "flex", alignItems: "center", gap: 10, cursor: "pointer", fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em" },
  adminMain: { padding: "32px clamp(18px, 3vw, 38px) 48px", minWidth: 0, boxSizing: "border-box" },
  adminShellMobile: { gridTemplateColumns: "1fr" },
  adminSidebarMobile: { position: "sticky", top: 0, zIndex: 160, height: "auto", padding: "12px 14px", gap: 12 },
  adminNavMobile: { display: "flex", gap: 8, marginTop: 12, overflowX: "auto", paddingBottom: 2 },
  adminMainMobile: { padding: "24px 16px 40px" },
  adminPageHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 18, marginBottom: 4, flexWrap: "wrap" },
};
