// ============================================================================
// POC chatbot — module isolé, activé par CHATBOT_ENABLED.
// Retrait : voir chatbot/README.md → "Procédure de désactivation / retrait".
// ============================================================================
// Styles isolés du module chatbot. Réutilise les tokens du theme principal.

import { T } from "../../frontend/src/theme";

export const chatStyles = {
  // ─── Bulle flottante côté client ─────────────────────────────────────────
  bubbleButton: {
    position: "fixed",
    bottom: 24,
    right: 24,
    width: 60,
    height: 60,
    borderRadius: 999,
    background: T.bleu,
    color: "#fff",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 14px 30px rgba(0,0,254,0.32)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 200,
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  bubbleButtonHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 18px 36px rgba(0,0,254,0.42)",
  },

  // ─── Panneau client ──────────────────────────────────────────────────────
  panel: {
    position: "fixed",
    bottom: 100,
    right: 24,
    width: "min(380px, calc(100vw - 32px))",
    height: "min(560px, calc(100vh - 140px))",
    background: "#fff",
    borderRadius: T.radiusL,
    boxShadow: "0 28px 70px rgba(0,0,0,0.22)",
    border: `1px solid ${T.border}`,
    display: "flex",
    flexDirection: "column",
    zIndex: 200,
    overflow: "hidden",
  },
  panelHeader: {
    background: T.deepBlack,
    color: "#fff",
    padding: "14px 18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  panelTitle: {
    fontSize: 14,
    fontWeight: 800,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  panelSubtitle: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    marginTop: 2,
  },
  panelClose: {
    width: 32,
    height: 32,
    borderRadius: 8,
    border: "1px solid rgba(255,255,255,0.16)",
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ─── Liste des messages ─────────────────────────────────────────────────
  messagesArea: {
    flex: 1,
    overflowY: "auto",
    padding: "16px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    background: T.ecru,
  },
  messageBase: {
    maxWidth: "85%",
    padding: "10px 14px",
    borderRadius: 14,
    fontSize: 14,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  messageUser: {
    alignSelf: "flex-end",
    background: T.bleu,
    color: "#fff",
    borderBottomRightRadius: 4,
  },
  messageAssistant: {
    alignSelf: "flex-start",
    background: "#fff",
    color: T.noir,
    border: `1px solid ${T.border}`,
    borderBottomLeftRadius: 4,
  },
  messageAdmin: {
    alignSelf: "flex-start",
    background: "rgba(35,107,56,0.10)",
    color: T.noir,
    border: `1px solid rgba(35,107,56,0.32)`,
    borderBottomLeftRadius: 4,
  },
  messageSystem: {
    alignSelf: "center",
    background: "transparent",
    color: T.textSoft,
    fontStyle: "italic",
    fontSize: 12,
    padding: "4px 8px",
  },
  messageMeta: {
    fontSize: 10,
    color: T.textSoft,
    marginTop: 4,
    letterSpacing: "0.02em",
  },
  messageMetaLight: {
    fontSize: 10,
    color: "rgba(255,255,255,0.7)",
    marginTop: 4,
  },

  // ─── Zone de saisie ─────────────────────────────────────────────────────
  inputArea: {
    padding: 12,
    borderTop: `1px solid ${T.border}`,
    background: "#fff",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  inputRow: {
    display: "flex",
    gap: 8,
    alignItems: "flex-end",
  },
  textarea: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    padding: "10px 12px",
    border: `1px solid ${T.border}`,
    borderRadius: 12,
    font: "inherit",
    fontSize: 14,
    resize: "none",
    outline: "none",
  },
  sendButton: {
    minHeight: 40,
    padding: "0 16px",
    border: "none",
    background: T.bleu,
    color: "#fff",
    borderRadius: 12,
    cursor: "pointer",
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    fontSize: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: {
    background: T.borderMid,
    cursor: "not-allowed",
  },
  escalateButton: {
    background: "transparent",
    border: `1px solid ${T.border}`,
    color: T.textSoft,
    padding: "6px 10px",
    borderRadius: 10,
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    alignSelf: "flex-start",
  },
  escalateButtonActive: {
    background: "rgba(159,29,29,0.08)",
    color: T.danger,
    borderColor: T.danger,
  },
  errorBanner: {
    padding: "8px 14px",
    background: "rgba(159,29,29,0.10)",
    color: T.danger,
    fontSize: 12,
    borderTop: `1px solid rgba(159,29,29,0.24)`,
  },
  typingIndicator: {
    alignSelf: "flex-start",
    color: T.textSoft,
    fontSize: 12,
    fontStyle: "italic",
    padding: "4px 14px",
  },

  // ─── Citations / cartes produit sous les réponses RAG (B1) ──────────────
  citationsRow: {
    alignSelf: "flex-start",
    maxWidth: "85%",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: -4,
    marginBottom: 4,
  },
  citationCard: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    background: "#fff",
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    textDecoration: "none",
    color: T.noir,
    fontSize: 12,
    cursor: "pointer",
    transition: "border-color 0.15s ease, transform 0.1s ease",
  },
  citationCardThumb: {
    width: 28,
    height: 28,
    borderRadius: 6,
    objectFit: "cover",
    background: T.ecru,
    flexShrink: 0,
  },
  citationCardTitle: {
    fontWeight: 700,
    fontSize: 12,
    lineHeight: 1.2,
    maxWidth: 130,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  citationCardSku: {
    fontSize: 10,
    color: T.textSoft,
    letterSpacing: "0.04em",
  },
  citationCardPrice: {
    fontSize: 11,
    fontWeight: 700,
    color: T.bleu,
    marginLeft: 4,
  },

  // ─── Feedback 👍/👎 sous chaque réponse assistant (B5) ──────────────────
  feedbackRow: {
    alignSelf: "flex-start",
    display: "flex",
    gap: 4,
    marginTop: -2,
    marginBottom: 4,
  },
  feedbackButton: {
    padding: "4px 6px",
    background: "transparent",
    border: `1px solid ${T.border}`,
    color: T.textSoft,
    borderRadius: 6,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    transition: "background 0.15s ease, color 0.15s ease, border-color 0.15s ease",
  },
  feedbackButtonActive: {
    background: T.bleuPale,
    color: T.bleu,
    borderColor: T.bleuBorder,
  },

  // ─── Page admin ─────────────────────────────────────────────────────────
  adminLayout: {
    display: "grid",
    gridTemplateColumns: "320px minmax(0, 1fr)",
    gap: 18,
    minHeight: "calc(100vh - 200px)",
  },
  adminLayoutMobile: {
    gridTemplateColumns: "1fr",
  },
  sessionsList: {
    background: "#fff",
    border: `1px solid ${T.border}`,
    borderRadius: T.radiusL,
    padding: 14,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minHeight: 0,
    overflowY: "auto",
    maxHeight: "calc(100vh - 220px)",
  },
  sessionItem: {
    padding: "12px 14px",
    border: `1px solid ${T.border}`,
    borderRadius: 12,
    cursor: "pointer",
    background: "#fff",
    display: "grid",
    gap: 4,
    transition: "background 0.15s ease, border-color 0.15s ease",
  },
  sessionItemActive: {
    background: T.bleuPale,
    borderColor: T.bleuBorder,
  },
  sessionItemTitle: {
    fontWeight: 700,
    fontSize: 13,
    color: T.noir,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sessionItemMeta: {
    fontSize: 11,
    color: T.textSoft,
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  statusBadge: {
    display: "inline-block",
    padding: "1px 8px",
    borderRadius: 999,
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  statusBadgeOpen: { background: "rgba(35,107,56,0.12)", color: T.success },
  statusBadgeEscalated: { background: "rgba(168,90,7,0.16)", color: "#a85a07" },
  statusBadgeClosed: { background: "rgba(0,0,0,0.08)", color: T.textSoft },

  conversationPanel: {
    background: "#fff",
    border: `1px solid ${T.border}`,
    borderRadius: T.radiusL,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    maxHeight: "calc(100vh - 220px)",
    overflow: "hidden",
  },
  conversationHeader: {
    padding: "14px 18px",
    borderBottom: `1px solid ${T.border}`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  filterTabs: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 12,
  },
  filterTab: {
    padding: "6px 12px",
    borderRadius: 999,
    border: `1px solid ${T.border}`,
    background: "transparent",
    color: T.noir,
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  filterTabActive: {
    background: T.noir,
    color: "#fff",
    borderColor: T.noir,
  },
};
